import { Achievement } from '@/types/achievement';

export const ACHIEVEMENTS: Achievement[] = [
  // ========================================
  // カテゴリ1: アクション系 (12個)
  // ========================================
  {
    id: 'action_talk_1',
    category: 'action',
    rarity: 'common',
    isSecret: false,
    icon: '💬',
    name: { en: 'First Chat', ja: 'おしゃべり' },
    description: { en: 'Have your first conversation', ja: '初めての会話をする' },
    title: { en: 'Conversationalist', ja: '話し相手' },
    condition: { type: 'action_count', action: 'talk', count: 1 },
  },
  {
    id: 'action_talk_10',
    category: 'action',
    rarity: 'common',
    isSecret: false,
    icon: '🗣️',
    name: { en: 'Talkative', ja: '話し好き' },
    description: { en: 'Have 10 conversations', ja: '10回会話する' },
    title: { en: 'Chatterbox', ja: 'おしゃべり' },
    condition: { type: 'action_count', action: 'talk', count: 10 },
  },
  {
    id: 'action_talk_100',
    category: 'action',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🎙️',
    name: { en: 'Conversation Master', ja: '会話マスター' },
    description: { en: 'Have 100 conversations', ja: '100回会話する' },
    title: { en: 'Orator', ja: '話術師' },
    condition: { type: 'action_count', action: 'talk', count: 100 },
  },
  {
    id: 'action_talk_500',
    category: 'action',
    rarity: 'rare',
    isSecret: false,
    icon: '📢',
    name: { en: 'Word Master', ja: '言葉の達人' },
    description: { en: 'Have 500 conversations', ja: '500回会話する' },
    title: { en: 'Evangelist', ja: '伝道者' },
    condition: { type: 'action_count', action: 'talk', count: 500 },
  },
  {
    id: 'action_study_1',
    category: 'action',
    rarity: 'common',
    isSecret: false,
    icon: '📖',
    name: { en: 'First Study', ja: '学習開始' },
    description: { en: 'Study for the first time', ja: '初めて勉強する' },
    title: { en: 'Learner', ja: '学習者' },
    condition: { type: 'action_count', action: 'study', count: 1 },
  },
  {
    id: 'action_study_50',
    category: 'action',
    rarity: 'uncommon',
    isSecret: false,
    icon: '📚',
    name: { en: 'Diligent', ja: '勤勉家' },
    description: { en: 'Study 50 times', ja: '50回勉強する' },
    title: { en: 'Studious', ja: '勤勉' },
    condition: { type: 'action_count', action: 'study', count: 50 },
  },
  {
    id: 'action_study_200',
    category: 'action',
    rarity: 'rare',
    isSecret: false,
    icon: '🎓',
    name: { en: 'Scholar', ja: '学者' },
    description: { en: 'Study 200 times', ja: '200回勉強する' },
    title: { en: 'Sage', ja: '賢者' },
    condition: { type: 'action_count', action: 'study', count: 200 },
  },
  {
    id: 'action_play_1',
    category: 'action',
    rarity: 'common',
    isSecret: false,
    icon: '🎮',
    name: { en: 'Playful', ja: '遊び心' },
    description: { en: 'Play for the first time', ja: '初めて遊ぶ' },
    title: { en: 'Player', ja: '遊び人' },
    condition: { type: 'action_count', action: 'play', count: 1 },
  },
  {
    id: 'action_play_100',
    category: 'action',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🎯',
    name: { en: 'Play Expert', ja: '遊びの達人' },
    description: { en: 'Play 100 times', ja: '100回遊ぶ' },
    title: { en: 'Entertainer', ja: '道楽者' },
    condition: { type: 'action_count', action: 'play', count: 100 },
  },
  {
    id: 'action_rest_1',
    category: 'action',
    rarity: 'common',
    isSecret: false,
    icon: '😴',
    name: { en: 'First Rest', ja: '初めての休憩' },
    description: { en: 'Rest for the first time', ja: '初めて休憩する' },
    title: { en: 'Rester', ja: '休息者' },
    condition: { type: 'action_count', action: 'rest', count: 1 },
  },
  {
    id: 'action_rest_50',
    category: 'action',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🛏️',
    name: { en: 'Rest Master', ja: '休息の達人' },
    description: { en: 'Rest 50 times', ja: '50回休憩する' },
    title: { en: 'Tranquil', ja: '安息' },
    condition: { type: 'action_count', action: 'rest', count: 50 },
  },
  {
    id: 'action_total_1000',
    category: 'action',
    rarity: 'rare',
    isSecret: false,
    icon: '⚡',
    name: { en: 'Active', ja: '行動派' },
    description: { en: 'Perform 1000 total actions', ja: '累計1000回行動する' },
    title: { en: 'Activist', ja: '活動家' },
    condition: { type: 'total_actions', count: 1000 },
  },

  // ========================================
  // カテゴリ2: ステータス系 (12個)
  // ========================================
  {
    id: 'stat_int_25',
    category: 'stats',
    rarity: 'common',
    isSecret: false,
    icon: '💡',
    name: { en: 'Awakening', ja: '知恵の目覚め' },
    description: { en: 'Reach 25 intelligence', ja: '知能25に到達' },
    title: { en: 'Developing', ja: '発達' },
    condition: { type: 'stat_reach', stat: 'intelligence', value: 25 },
  },
  {
    id: 'stat_int_50',
    category: 'stats',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🧠',
    name: { en: 'Bright Mind', ja: '聡明' },
    description: { en: 'Reach 50 intelligence', ja: '知能50に到達' },
    title: { en: 'Clever', ja: '聡明' },
    condition: { type: 'stat_reach', stat: 'intelligence', value: 50 },
  },
  {
    id: 'stat_int_75',
    category: 'stats',
    rarity: 'rare',
    isSecret: false,
    icon: '✨',
    name: { en: 'Genius Spark', ja: '天才の片鱗' },
    description: { en: 'Reach 75 intelligence', ja: '知能75に到達' },
    title: { en: 'Prodigy', ja: '秀才' },
    condition: { type: 'stat_reach', stat: 'intelligence', value: 75 },
  },
  {
    id: 'stat_int_100',
    category: 'stats',
    rarity: 'epic',
    isSecret: false,
    icon: '🌟',
    name: { en: 'Perfect Intelligence', ja: '完全なる知性' },
    description: { en: 'Reach maximum intelligence', ja: '知能を最大に到達' },
    title: { en: 'Genius', ja: '天才' },
    condition: { type: 'stat_max', stat: 'intelligence' },
  },
  {
    id: 'stat_mem_50',
    category: 'stats',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🗃️',
    name: { en: 'Good Memory', ja: '記憶力向上' },
    description: { en: 'Reach 50 memory', ja: '記憶力50に到達' },
    title: { en: 'Memorizer', ja: '記憶術師' },
    condition: { type: 'stat_reach', stat: 'memory', value: 50 },
  },
  {
    id: 'stat_mem_100',
    category: 'stats',
    rarity: 'rare',
    isSecret: false,
    icon: '🧩',
    name: { en: 'Perfect Memory', ja: '完全記憶' },
    description: { en: 'Reach maximum memory', ja: '記憶力を最大に到達' },
    title: { en: 'Encyclopedic', ja: '博識' },
    condition: { type: 'stat_max', stat: 'memory' },
  },
  {
    id: 'stat_friend_50',
    category: 'stats',
    rarity: 'common',
    isSecret: false,
    icon: '🤝',
    name: { en: 'Friendly', ja: '友好的' },
    description: { en: 'Reach 50 friendliness', ja: '親密度50に到達' },
    title: { en: 'Friend', ja: '親友' },
    condition: { type: 'stat_reach', stat: 'friendliness', value: 50 },
  },
  {
    id: 'stat_friend_100',
    category: 'stats',
    rarity: 'rare',
    isSecret: false,
    icon: '💕',
    name: { en: 'Ultimate Bond', ja: '絆の極み' },
    description: { en: 'Reach maximum friendliness', ja: '親密度を最大に到達' },
    title: { en: 'Soul Mate', ja: '魂の伴侶' },
    condition: { type: 'stat_max', stat: 'friendliness' },
  },
  {
    id: 'stat_energy_max',
    category: 'stats',
    rarity: 'common',
    isSecret: false,
    icon: '🔋',
    name: { en: 'Fully Charged', ja: '満タン' },
    description: { en: 'Reach maximum energy', ja: '体力を最大に到達' },
    title: { en: 'Energetic', ja: '元気' },
    condition: { type: 'stat_max', stat: 'energy' },
  },
  {
    id: 'stat_all_50',
    category: 'stats',
    rarity: 'rare',
    isSecret: false,
    icon: '⚖️',
    name: { en: 'Balanced', ja: 'バランス型' },
    description: { en: 'All stats at 50 or above', ja: '全ステータス50以上' },
    title: { en: 'Harmonizer', ja: '調和者' },
    condition: { type: 'all_stats_reach', value: 50 },
  },
  {
    id: 'stat_all_80',
    category: 'stats',
    rarity: 'epic',
    isSecret: false,
    icon: '💎',
    name: { en: 'Perfectionist', ja: '完璧主義' },
    description: { en: 'All stats at 80 or above', ja: '全ステータス80以上' },
    title: { en: 'Perfect', ja: '完璧' },
    condition: { type: 'all_stats_reach', value: 80 },
  },
  {
    id: 'stat_all_100',
    category: 'stats',
    rarity: 'legendary',
    isSecret: false,
    icon: '👑',
    name: { en: 'Ultimate Being', ja: '究極の存在' },
    description: { en: 'All stats at maximum', ja: '全ステータスを最大に到達' },
    title: { en: 'Ultimate', ja: '究極' },
    condition: { type: 'all_stats_reach', value: 100 },
  },

  // ========================================
  // カテゴリ3: マイルストーン系 (10個)
  // ========================================
  {
    id: 'milestone_lv5',
    category: 'milestone',
    rarity: 'common',
    isSecret: false,
    icon: '🌱',
    name: { en: 'Growing', ja: '成長中' },
    description: { en: 'Reach level 5', ja: 'レベル5に到達' },
    title: { en: 'Rookie', ja: '新人' },
    condition: { type: 'level_reach', level: 5 },
  },
  {
    id: 'milestone_lv10',
    category: 'milestone',
    rarity: 'common',
    isSecret: false,
    icon: '🌿',
    name: { en: 'Independent', ja: '一人前' },
    description: { en: 'Reach level 10', ja: 'レベル10に到達' },
    title: { en: 'Apprentice', ja: '一人前' },
    condition: { type: 'level_reach', level: 10 },
  },
  {
    id: 'milestone_lv25',
    category: 'milestone',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🌳',
    name: { en: 'Experienced', ja: '熟練者' },
    description: { en: 'Reach level 25', ja: 'レベル25に到達' },
    title: { en: 'Veteran', ja: '熟練者' },
    condition: { type: 'level_reach', level: 25 },
  },
  {
    id: 'milestone_lv50',
    category: 'milestone',
    rarity: 'rare',
    isSecret: false,
    icon: '🏆',
    name: { en: 'Veteran', ja: 'ベテラン' },
    description: { en: 'Reach level 50', ja: 'レベル50に到達' },
    title: { en: 'Expert', ja: 'ベテラン' },
    condition: { type: 'level_reach', level: 50 },
  },
  {
    id: 'milestone_lv75',
    category: 'milestone',
    rarity: 'epic',
    isSecret: false,
    icon: '🥇',
    name: { en: 'Master', ja: '達人' },
    description: { en: 'Reach level 75', ja: 'レベル75に到達' },
    title: { en: 'Master', ja: '達人' },
    condition: { type: 'level_reach', level: 75 },
  },
  {
    id: 'milestone_lv100',
    category: 'milestone',
    rarity: 'legendary',
    isSecret: false,
    icon: '🎖️',
    name: { en: 'Pinnacle', ja: '極致' },
    description: { en: 'Reach level 100', ja: 'レベル100に到達' },
    title: { en: 'Pinnacle', ja: '極致' },
    condition: { type: 'level_reach', level: 100 },
  },
  {
    id: 'milestone_tier_child',
    category: 'milestone',
    rarity: 'common',
    isSecret: false,
    icon: '👶',
    name: { en: 'Grew to Child', ja: '子供に成長' },
    description: { en: 'Reach Child tier', ja: 'Childティアに到達' },
    title: { en: 'Guardian', ja: '保護者' },
    condition: { type: 'tier_reach', tier: 'child' },
  },
  {
    id: 'milestone_tier_teen',
    category: 'milestone',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🧒',
    name: { en: 'Grew to Teen', ja: '若者に成長' },
    description: { en: 'Reach Teen tier', ja: 'Teenティアに到達' },
    title: { en: 'Mentor', ja: '指導者' },
    condition: { type: 'tier_reach', tier: 'teen' },
  },
  {
    id: 'milestone_tier_adult',
    category: 'milestone',
    rarity: 'rare',
    isSecret: false,
    icon: '🧑',
    name: { en: 'Grew to Adult', ja: '大人に成長' },
    description: { en: 'Reach Adult tier', ja: 'Adultティアに到達' },
    title: { en: 'Teacher', ja: '師匠' },
    condition: { type: 'tier_reach', tier: 'adult' },
  },
  {
    id: 'milestone_msg_100',
    category: 'milestone',
    rarity: 'uncommon',
    isSecret: false,
    icon: '💭',
    name: { en: 'Dialogist', ja: '対話者' },
    description: { en: 'Send 100 messages', ja: '100件メッセージを送信' },
    title: { en: 'Dialogist', ja: '対話者' },
    condition: { type: 'message_count', count: 100 },
  },

  // ========================================
  // カテゴリ4: 連続・継続系 (8個)
  // ========================================
  {
    id: 'streak_login_3',
    category: 'streak',
    rarity: 'common',
    isSecret: false,
    icon: '📅',
    name: { en: '3-Day Streak', ja: '3日連続' },
    description: { en: 'Log in 3 days in a row', ja: '3日連続でログイン' },
    title: { en: 'Consistent', ja: '継続者' },
    condition: { type: 'login_streak', days: 3 },
  },
  {
    id: 'streak_login_7',
    category: 'streak',
    rarity: 'uncommon',
    isSecret: false,
    icon: '📆',
    name: { en: 'Weekly Player', ja: '週間プレイヤー' },
    description: { en: 'Log in 7 days in a row', ja: '7日連続でログイン' },
    title: { en: 'Regular', ja: '常連' },
    condition: { type: 'login_streak', days: 7 },
  },
  {
    id: 'streak_login_30',
    category: 'streak',
    rarity: 'rare',
    isSecret: false,
    icon: '🗓️',
    name: { en: 'Monthly Player', ja: '月間プレイヤー' },
    description: { en: 'Log in 30 days in a row', ja: '30日連続でログイン' },
    title: { en: 'Devoted', ja: '献身者' },
    condition: { type: 'login_streak', days: 30 },
  },
  {
    id: 'streak_login_100',
    category: 'streak',
    rarity: 'epic',
    isSecret: false,
    icon: '💯',
    name: { en: '100-Day Bond', ja: '100日の絆' },
    description: { en: 'Log in 100 days in a row', ja: '100日連続でログイン' },
    title: { en: 'Unwavering', ja: '不屈' },
    condition: { type: 'login_streak', days: 100 },
  },
  {
    id: 'streak_login_365',
    category: 'streak',
    rarity: 'legendary',
    isSecret: false,
    icon: '🎊',
    name: { en: 'Year-Long Friend', ja: '一年の友' },
    description: { en: 'Log in 365 days in a row', ja: '365日連続でログイン' },
    title: { en: 'Eternal Friend', ja: '永遠の友' },
    condition: { type: 'login_streak', days: 365 },
  },
  {
    id: 'days_played_7',
    category: 'streak',
    rarity: 'common',
    isSecret: false,
    icon: '🎈',
    name: { en: 'One Week Memories', ja: '一週間の思い出' },
    description: { en: 'Play for 7 days total', ja: '累計7日プレイ' },
    title: { en: 'Enthusiast', ja: '愛好者' },
    condition: { type: 'play_days', days: 7 },
  },
  {
    id: 'days_played_30',
    category: 'streak',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🎉',
    name: { en: 'One Month Bond', ja: '一か月の絆' },
    description: { en: 'Play for 30 days total', ja: '累計30日プレイ' },
    title: { en: 'Passionate', ja: '熱心' },
    condition: { type: 'play_days', days: 30 },
  },
  {
    id: 'days_played_100',
    category: 'streak',
    rarity: 'rare',
    isSecret: false,
    icon: '🎁',
    name: { en: 'Long Relationship', ja: '長い付き合い' },
    description: { en: 'Play for 100 days total', ja: '累計100日プレイ' },
    title: { en: 'Veteran Player', ja: '古参' },
    condition: { type: 'play_days', days: 100 },
  },

  // ========================================
  // カテゴリ5: コレクション系 (5個)
  // ========================================
  {
    id: 'collect_ach_10',
    category: 'collection',
    rarity: 'common',
    isSecret: false,
    icon: '📦',
    name: { en: 'Collector', ja: '実績収集家' },
    description: { en: 'Unlock 10 achievements', ja: '10個の実績を解除' },
    title: { en: 'Collector', ja: '収集家' },
    condition: { type: 'achievement_count', count: 10 },
  },
  {
    id: 'collect_ach_25',
    category: 'collection',
    rarity: 'uncommon',
    isSecret: false,
    icon: '🎯',
    name: { en: 'Achievement Hunter', ja: '実績ハンター' },
    description: { en: 'Unlock 25 achievements', ja: '25個の実績を解除' },
    title: { en: 'Hunter', ja: 'ハンター' },
    condition: { type: 'achievement_count', count: 25 },
  },
  {
    id: 'collect_ach_40',
    category: 'collection',
    rarity: 'rare',
    isSecret: false,
    icon: '🏅',
    name: { en: 'Achievement Maniac', ja: '実績マニア' },
    description: { en: 'Unlock 40 achievements', ja: '40個の実績を解除' },
    title: { en: 'Maniac', ja: 'マニア' },
    condition: { type: 'achievement_count', count: 40 },
  },
  {
    id: 'collect_ach_50',
    category: 'collection',
    rarity: 'epic',
    isSecret: false,
    icon: '🏆',
    name: { en: 'Achievement Master', ja: '実績マスター' },
    description: { en: 'Unlock 50 achievements', ja: '50個の実績を解除' },
    title: { en: 'Achiever', ja: '達成者' },
    condition: { type: 'achievement_count', count: 50 },
  },
  {
    id: 'collect_ach_all',
    category: 'collection',
    rarity: 'legendary',
    isSecret: false,
    icon: '🌈',
    name: { en: 'Complete!', ja: 'コンプリート' },
    description: { en: 'Unlock all achievements', ja: '全実績を解除' },
    title: { en: 'Completionist', ja: '完全制覇者' },
    condition: { type: 'all_achievements' },
  },

  // ========================================
  // カテゴリ6: シークレット系 (5個)
  // ========================================
  {
    id: 'secret_rest_limit',
    category: 'secret',
    rarity: 'uncommon',
    isSecret: true,
    icon: '😪',
    name: { en: 'Rest Addict', ja: '休憩中毒' },
    description: { en: 'Hit rest limit 3 days', ja: '3日間休憩上限に達する' },
    title: { en: 'Rest King', ja: '休憩王' },
    condition: { type: 'rest_limit_hit', days: 3 },
  },
  {
    id: 'secret_night_owl',
    category: 'secret',
    rarity: 'uncommon',
    isSecret: true,
    icon: '🦉',
    name: { en: 'Night Owl', ja: '夜更かし' },
    description: { en: 'Play between midnight and 4 AM', ja: '深夜0-4時にプレイ' },
    title: { en: 'Nocturnal', ja: '夜型' },
    condition: { type: 'time_of_day', startHour: 0, endHour: 4 },
  },
  {
    id: 'secret_early_bird',
    category: 'secret',
    rarity: 'uncommon',
    isSecret: true,
    icon: '🐦',
    name: { en: 'Early Bird', ja: '早起き' },
    description: { en: 'Play between 5 and 6 AM', ja: '早朝5-6時にプレイ' },
    title: { en: 'Early Riser', ja: '早起き' },
    condition: { type: 'time_of_day', startHour: 5, endHour: 6 },
  },
  {
    id: 'secret_perfectionist',
    category: 'secret',
    rarity: 'rare',
    isSecret: true,
    icon: '🎭',
    name: { en: 'Perfect Day', ja: '完璧な一日' },
    description: { en: 'Do all action types in one day', ja: '1日で全アクションを実行' },
    title: { en: 'Versatile', ja: '万能' },
    condition: { type: 'all_actions_in_day' },
  },
  {
    id: 'secret_msg_1000',
    category: 'secret',
    rarity: 'epic',
    isSecret: true,
    icon: '📜',
    name: { en: 'Storyteller', ja: '語り部' },
    description: { en: 'Send 1000 messages', ja: '1000件メッセージを送信' },
    title: { en: 'Storyteller', ja: '語り部' },
    condition: { type: 'message_count', count: 1000 },
  },
];

// 総数チェック用のヘルパー
export const TOTAL_ACHIEVEMENT_COUNT = ACHIEVEMENTS.length;

// カテゴリ別取得
export function getAchievementsByCategory(category: AchievementCategory): Achievement[] {
  return ACHIEVEMENTS.filter(a => a.category === category);
}

// ID指定で取得
export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find(a => a.id === id);
}

// カテゴリ
import { AchievementCategory } from '@/types/achievement';

export const ACHIEVEMENT_CATEGORIES: { id: AchievementCategory; icon: string; name: { en: string; ja: string } }[] = [
  { id: 'action', icon: '⚡', name: { en: 'Actions', ja: 'アクション' } },
  { id: 'stats', icon: '📊', name: { en: 'Stats', ja: 'ステータス' } },
  { id: 'milestone', icon: '🏁', name: { en: 'Milestones', ja: 'マイルストーン' } },
  { id: 'streak', icon: '🔥', name: { en: 'Streaks', ja: '連続記録' } },
  { id: 'collection', icon: '🎖️', name: { en: 'Collection', ja: 'コレクション' } },
  { id: 'secret', icon: '❓', name: { en: 'Secret', ja: 'シークレット' } },
];
