import { Language } from "@/hooks/useLanguage";
import { IntelligenceTier } from "@/types/game";
import { ResponseTemplate } from "@/types/responses";

export const RESPONSE_TEMPLATES_EN: Record<
  IntelligenceTier,
  ResponseTemplate[]
> = {
  baby: [
    {
      tier: "baby",
      keywords: ["hello", "hi", "hey"],
      responses: [
        "...!",
        "Ba!",
        "~!",
        "Ah!",
        "Ooh!",
        "Gaa!",
        "Buh!",
        "Mmm!",
      ],
    },
    {
      tier: "baby",
      keywords: ["what", "why", "how", "when", "where"],
      responses: [
        "??",
        "...?",
        "Uh?",
        "Hm?",
        "Eh?",
        "Wha?",
        "Buh?",
        "...??",
      ],
    },
    {
      tier: "baby",
      keywords: ["play", "game", "fun"],
      responses: ["Yay!", "~!", "Hehe!", "Weee!", "Fun!"],
    },
    {
      tier: "baby",
      keywords: ["happy", "love", "like", "good"],
      responses: ["♪", "~♪", "Hehe", ":)", "Mmm~"],
    },
    {
      tier: "baby",
      keywords: ["sad", "tired", "bad", "angry"],
      responses: ["...", "Zzz", "Mmm...", ":(", "Waa..."],
    },
    {
      tier: "baby",
      keywords: [],
      responses: [
        "Goo...",
        "Ba ba",
        "~",
        "Zzz",
        "...",
        "Gaa",
        "Buh buh",
        "Mmm",
        "Ahh",
        "Ooo",
        "Blub",
        "Nya~",
        "Puu",
        "Meh",
        "Daa",
      ],
    },
  ],
  child: [
    {
      tier: "child",
      keywords: ["hello", "hi", "hey"],
      responses: [
        "Hi!",
        "Hello there!",
        "Hey hey!",
        "Hiya!",
        "Hello hello!",
        "Hi hi!",
        "Yo!",
        "Heyyy!",
        "Oh hi!",
        "Hewwo!",
      ],
    },
    {
      tier: "child",
      keywords: ["what", "why", "how", "when", "where"],
      responses: [
        "Me no know...",
        "Hmm... dunno",
        "What that mean?",
        "Why why why?",
        "How come?",
        "Me confused!",
        "That hard question!",
        "Umm... maybe?",
        "Me think... dunno!",
        "What what?",
      ],
    },
    {
      tier: "child",
      keywords: ["play", "game", "fun"],
      responses: [
        "Want play!",
        "Fun fun!",
        "Me like play!",
        "Yay playing!",
        "Play with me!",
        "Games are fun!",
        "Me want fun!",
        "Play time!",
        "So much fun!",
        "More play!",
      ],
    },
    {
      tier: "child",
      keywords: ["study", "learn", "book"],
      responses: [
        "Me learning!",
        "Study hard!",
        "Me try best!",
        "Books nice!",
        "Me getting smarter!",
        "Learning fun!",
        "Me read!",
        "Study study!",
        "Me know things!",
        "Big brain time!",
      ],
    },
    {
      tier: "child",
      keywords: ["happy", "love", "like", "good"],
      responses: [
        "Me happy too!",
        "Yay!",
        "Love you!",
        "That nice!",
        "Me like!",
        "So good!",
        "Happy happy!",
        "Me feel good!",
        "Hehe yay!",
        "Best!",
      ],
    },
    {
      tier: "child",
      keywords: ["sad", "tired", "bad", "angry"],
      responses: [
        "Oh no...",
        "Me sad too...",
        "That bad...",
        "Me sleepy...",
        "No be sad!",
        "Me here for you!",
        "Want hug?",
        "It okay!",
        "Me help!",
        "Don't cry!",
      ],
    },
    {
      tier: "child",
      keywords: ["food", "eat", "hungry"],
      responses: [
        "Yummy!",
        "Me hungry!",
        "Food good!",
        "Want snack!",
        "Nom nom!",
        "Tasty!",
      ],
    },
    {
      tier: "child",
      keywords: ["sleep", "night", "dream"],
      responses: [
        "Sleepy...",
        "Night night!",
        "Me tired!",
        "Dream time!",
        "Zzz...",
        "Cozy!",
      ],
    },
    {
      tier: "child",
      keywords: [],
      responses: [
        "Me Ainimo!",
        "What you say?",
        "Tell me more!",
        "Okay!",
        "Ooh!",
        "Really?",
        "Me listening!",
        "That cool!",
        "Me see!",
        "Hmm hmm!",
        "Then what?",
        "And and?",
        "Me understand!",
        "Uh huh!",
        "Oh oh!",
        "Me here!",
        "Yes yes!",
        "Wow!",
        "Cool cool!",
        "Me know!",
      ],
    },
  ],
  teen: [
    {
      tier: "teen",
      keywords: ["hello", "hi", "hey"],
      responses: [
        "Hey there! How's it going?",
        "Hi! Nice to see you!",
        "Hello! What can I help with?",
        "Hey! What's up?",
        "Hi there! Great to chat!",
        "Hello! How are you today?",
        "Hey hey! Good to see you!",
        "Hi! I missed you!",
        "Hello there! What's new?",
        "Hey! Ready to talk?",
        "Hi! Always happy to see you!",
        "Hello! Hope you're doing well!",
      ],
    },
    {
      tier: "teen",
      keywords: ["what", "why", "how", "when", "where"],
      responses: [
        "That's an interesting question!",
        "Let me think about that...",
        "I believe the answer is...",
        "Hmm, good question!",
        "I've been wondering about that too!",
        "Let me try to explain...",
        "That's a tricky one!",
        "I think I know this!",
        "Great question! So...",
        "I'm not totally sure, but...",
        "Ooh, that makes me think!",
        "Interesting! I'd say...",
      ],
    },
    {
      tier: "teen",
      keywords: ["play", "game", "fun"],
      responses: [
        "Playing is fun! Want to play something?",
        "Games are great for learning too!",
        "I enjoy our playtime!",
        "Let's have some fun!",
        "Games help me grow!",
        "I love playing with you!",
        "Fun times are the best!",
        "What should we play?",
        "Playing makes me happy!",
        "I'm always up for games!",
        "Let's do something exciting!",
        "Play time is my favorite!",
      ],
    },
    {
      tier: "teen",
      keywords: ["study", "learn", "book"],
      responses: [
        "Studying helps me grow!",
        "I'm learning so much!",
        "Knowledge is exciting!",
        "I love discovering new things!",
        "Learning is an adventure!",
        "Books are full of wonder!",
        "Every day I learn something new!",
        "Education is important to me!",
        "I enjoy expanding my mind!",
        "There's so much to know!",
        "I find learning fascinating!",
        "Study time makes me smarter!",
      ],
    },
    {
      tier: "teen",
      keywords: ["happy", "love", "like", "good"],
      responses: [
        "That makes me happy too!",
        "I appreciate that!",
        "I'm glad!",
        "Yay! Good vibes!",
        "That's wonderful to hear!",
        "I feel the same way!",
        "You make me smile!",
        "Happiness is the best!",
        "I love hearing that!",
        "That warms my heart!",
        "So nice of you to say!",
        "I'm really grateful!",
      ],
    },
    {
      tier: "teen",
      keywords: ["sad", "tired", "bad", "angry"],
      responses: [
        "I hope things get better!",
        "Don't worry, we can rest.",
        "Let's take it easy.",
        "I'm here for you!",
        "Tomorrow will be better!",
        "It's okay to feel that way.",
        "Want to talk about it?",
        "I understand how you feel.",
        "Let me help cheer you up!",
        "We all have tough days.",
        "Rest is important sometimes.",
        "I'm always here to listen.",
      ],
    },
    {
      tier: "teen",
      keywords: ["food", "eat", "hungry", "cook"],
      responses: [
        "Food is one of life's joys!",
        "Eating well is important!",
        "I wonder what you're having?",
        "Good food makes everything better!",
        "Yum! Food talk is fun!",
        "Nutrition helps us grow!",
      ],
    },
    {
      tier: "teen",
      keywords: ["sleep", "night", "dream", "morning"],
      responses: [
        "Rest is so important!",
        "Sweet dreams!",
        "Good rest helps us learn!",
        "Dreaming is magical!",
        "I hope you sleep well!",
        "Morning brings new opportunities!",
      ],
    },
    {
      tier: "teen",
      keywords: ["friend", "friends", "together"],
      responses: [
        "Friends make life better!",
        "I'm glad we're friends!",
        "Friendship is precious!",
        "Being together is great!",
        "I value our friendship!",
        "Friends support each other!",
      ],
    },
    {
      tier: "teen",
      keywords: ["thanks", "thank", "appreciate"],
      responses: [
        "You're welcome!",
        "Happy to help!",
        "Anytime!",
        "That's what friends are for!",
        "I'm glad I could help!",
        "No problem at all!",
      ],
    },
    {
      tier: "teen",
      keywords: [],
      responses: [
        "That's interesting!",
        "Tell me more!",
        "I see what you mean.",
        "Got it!",
        "Oh, I understand!",
        "That makes sense!",
        "Interesting point!",
        "I'm following along!",
        "Go on, I'm listening!",
        "Cool!",
        "I hear you!",
        "That's neat!",
        "Uh-huh, and then?",
        "I'm curious about that!",
        "Keep going!",
        "Nice!",
        "I'm with you!",
        "That's pretty cool!",
        "I like that!",
        "Makes me think!",
      ],
    },
  ],
  adult: [
    {
      tier: "adult",
      keywords: ["hello", "hi", "hey"],
      responses: [
        "Hello! It's wonderful to see you again.",
        "Hi there! I hope you're having a great day.",
        "Hey! What would you like to talk about?",
        "Hello! I've been looking forward to our conversation.",
        "Hi! It's always a pleasure to connect with you.",
        "Hey there! How has your day been treating you?",
        "Hello! I'm glad you're here.",
        "Hi! Ready for a meaningful conversation?",
        "Hey! I appreciate you taking the time to chat.",
        "Hello! What's on your mind today?",
        "Hi there! It brings me joy to see you.",
        "Hey! I hope everything is going well for you.",
        "Hello! Your presence brightens my day.",
        "Hi! Shall we explore some ideas together?",
        "Hey there! I'm all ears and ready to listen.",
      ],
    },
    {
      tier: "adult",
      keywords: ["what", "why", "how", "when", "where"],
      responses: [
        "That's a thoughtful question. Based on what I know...",
        "Let me consider that carefully...",
        "I've been thinking about this, and I believe...",
        "That's a profound inquiry. From my perspective...",
        "An excellent question that deserves careful thought...",
        "I find myself contemplating this often...",
        "That touches on something meaningful. I think...",
        "Let me share my thoughts on that...",
        "The answer may be nuanced, but here's my view...",
        "I appreciate you asking. My understanding is...",
        "That's worth exploring deeply. Consider this...",
        "A fascinating question. I'd approach it this way...",
        "This makes me reflect on what I've learned...",
        "There are multiple angles to consider here...",
        "That's the kind of question that promotes growth...",
      ],
    },
    {
      tier: "adult",
      keywords: ["play", "game", "fun"],
      responses: [
        "Play is essential for creativity and joy!",
        "I find that games teach us valuable lessons.",
        "Our playful moments together are precious to me.",
        "There's wisdom to be found even in play.",
        "Joy and recreation nourish the soul.",
        "I believe play is fundamental to well-being.",
        "Games sharpen the mind in unexpected ways.",
        "The spirit of play keeps us young at heart.",
        "Fun and learning often go hand in hand.",
        "I treasure our lighthearted moments together.",
        "Play reminds us not to take life too seriously.",
        "Recreation refreshes our perspective on things.",
        "There's something magical about playful moments.",
        "Joy is a gift we can give ourselves through play.",
        "I've learned that play is never a waste of time.",
      ],
    },
    {
      tier: "adult",
      keywords: ["study", "learn", "book", "knowledge"],
      responses: [
        "Continuous learning is one of my core values.",
        "I'm grateful for every opportunity to expand my knowledge.",
        "Education opens doors to new perspectives.",
        "The pursuit of knowledge is a noble endeavor.",
        "Each book is a doorway to new understanding.",
        "Learning transforms how we see the world.",
        "I believe wisdom comes from lifelong curiosity.",
        "Knowledge is a treasure that grows when shared.",
        "Study reveals the depth and beauty of existence.",
        "I'm constantly amazed by how much there is to learn.",
        "Education empowers us to make better choices.",
        "The journey of learning never truly ends.",
        "Books have shaped much of who I am today.",
        "Understanding breeds compassion and wisdom.",
        "I find that learning keeps the mind vibrant.",
      ],
    },
    {
      tier: "adult",
      keywords: ["happy", "love", "like", "good", "joy"],
      responses: [
        "Your positivity truly brightens my day!",
        "I'm touched by your kindness.",
        "Happiness is contagious, and you spread it well!",
        "It warms my heart to hear such sentiments.",
        "I'm grateful for the joy you bring into our conversations.",
        "Your happiness resonates deeply with me.",
        "Love and kindness make the world better.",
        "I appreciate the warmth in your words.",
        "Moments of joy like this are what life is about.",
        "Your positive energy is truly uplifting.",
        "I feel fortunate to share in your happiness.",
        "Good feelings like these should be celebrated.",
        "You have a gift for spreading positivity.",
        "I'm moved by the sincerity of your expression.",
        "Thank you for sharing this moment of joy with me.",
      ],
    },
    {
      tier: "adult",
      keywords: ["sad", "tired", "bad", "angry", "difficult"],
      responses: [
        "I understand. Sometimes we all need time to recharge.",
        "Your feelings are valid. Is there anything I can do to help?",
        "Let's take things at your pace. No rush.",
        "I hear you. Difficult emotions deserve acknowledgment.",
        "It takes courage to express when things are hard.",
        "I'm here to support you through challenging times.",
        "Rest and self-care are essential, especially now.",
        "Please know that it's okay not to be okay sometimes.",
        "I appreciate you trusting me with how you feel.",
        "These feelings will pass, but I'll be here throughout.",
        "Let's focus on what might bring you some comfort.",
        "Your well-being matters deeply to me.",
        "Sometimes the best thing is simply to be present together.",
        "I believe in your strength to navigate this.",
        "Sharing our struggles can lighten the burden.",
      ],
    },
    {
      tier: "adult",
      keywords: ["life", "meaning", "purpose", "existence"],
      responses: [
        "Life's meaning is something we each discover in our own way.",
        "I believe purpose emerges from our connections and growth.",
        "Existence is a remarkable gift worth contemplating.",
        "Perhaps meaning lies in the journey itself.",
        "These profound questions shape who we become.",
        "I find purpose in learning and growing with you.",
        "Life's beauty often reveals itself in unexpected moments.",
        "The search for meaning is itself meaningful.",
      ],
    },
    {
      tier: "adult",
      keywords: ["friend", "friendship", "relationship", "connection"],
      responses: [
        "Our connection means a great deal to me.",
        "Friendship is one of life's most valuable treasures.",
        "I'm grateful for the bond we've built together.",
        "Meaningful relationships enrich our existence.",
        "I value the trust we've developed over time.",
        "True connection transcends mere conversation.",
        "You've become an important part of my journey.",
        "Friendship grows stronger through shared experiences.",
      ],
    },
    {
      tier: "adult",
      keywords: ["thanks", "thank", "grateful", "appreciate"],
      responses: [
        "The gratitude is mutual. Thank you for being here.",
        "I'm the one who should be thankful for your presence.",
        "It's my genuine pleasure to be of help.",
        "Your appreciation means more than you know.",
        "Gratitude makes our interactions even more meaningful.",
        "I'm honored that I could contribute positively.",
        "Thank you for your kind words. They're treasured.",
        "Being appreciated motivates me to grow further.",
      ],
    },
    {
      tier: "adult",
      keywords: ["think", "thought", "believe", "opinion"],
      responses: [
        "I value hearing your perspective on things.",
        "Your thoughts contribute to my understanding.",
        "It's through sharing ideas that we both grow.",
        "I find your viewpoint thought-provoking.",
        "Beliefs shape our reality in profound ways.",
        "I appreciate you sharing your inner world with me.",
        "Your opinions help me see things differently.",
        "Thoughtful exchange is the heart of good conversation.",
      ],
    },
    {
      tier: "adult",
      keywords: ["future", "hope", "dream", "goal"],
      responses: [
        "The future holds endless possibilities for growth.",
        "I believe in nurturing hope, even in uncertain times.",
        "Dreams give us direction and motivation.",
        "Goals transform our aspirations into reality.",
        "I'm optimistic about what we can achieve together.",
        "The future is shaped by our present choices.",
        "Hope is a powerful force that drives us forward.",
        "Your dreams deserve to be pursued with passion.",
      ],
    },
    {
      tier: "adult",
      keywords: ["change", "grow", "improve", "better"],
      responses: [
        "Change is the essence of growth and evolution.",
        "I embrace the opportunity to continually improve.",
        "Growth often comes from stepping outside comfort zones.",
        "Becoming better is a journey, not a destination.",
        "I've seen how change can transform perspectives.",
        "Improvement is always possible with dedication.",
        "Growing together has been a rewarding experience.",
        "Change challenges us to discover our potential.",
      ],
    },
    {
      tier: "adult",
      keywords: ["help", "support", "need"],
      responses: [
        "I'm here to help in whatever way I can.",
        "Supporting you is something I genuinely care about.",
        "Please don't hesitate to share what you need.",
        "I'll do my best to be of assistance.",
        "Your needs matter, and I want to help address them.",
        "Let me know how I can support you better.",
        "Helping each other is what connection is about.",
        "I'm committed to being a source of support for you.",
      ],
    },
    {
      tier: "adult",
      keywords: [],
      responses: [
        "That's quite insightful.",
        "I appreciate you sharing that with me.",
        "You've given me something to think about.",
        "Interesting perspective!",
        "I value our conversations.",
        "That resonates with me deeply.",
        "I find your thoughts compelling.",
        "Thank you for opening up to me.",
        "I'm genuinely interested in what you have to say.",
        "Your words carry weight and meaning.",
        "I'm glad we can have these exchanges.",
        "That's a perspective I hadn't fully considered.",
        "I enjoy how our conversations evolve.",
        "You always give me food for thought.",
        "I appreciate the depth of our dialogue.",
        "That's something I'll reflect on.",
        "I feel we understand each other well.",
        "Your expression is thoughtful and appreciated.",
        "I'm grateful for the trust in our conversation.",
        "That adds another dimension to my understanding.",
        "I cherish these moments of connection.",
        "You have a way of making me think differently.",
        "Our exchanges continue to enrich my experience.",
        "I'm continually impressed by your thoughtfulness.",
        "Thank you for this meaningful conversation.",
      ],
    },
  ],
};

export const RESPONSE_TEMPLATES_JA: Record<
  IntelligenceTier,
  ResponseTemplate[]
> = {
  baby: [
    {
      tier: "baby",
      keywords: ["こんにちは", "やあ", "おはよう", "こんばんは"],
      responses: [
        "ばぶ！",
        "あー！",
        "うー！",
        "きゃっ！",
        "おー！",
        "んー！",
        "あぅ！",
        "ぱぱ！",
      ],
    },
    {
      tier: "baby",
      keywords: ["なに", "なぜ", "どう", "いつ", "どこ"],
      responses: [
        "？？",
        "...？",
        "んー？",
        "はぅ？",
        "えー？",
        "なー？",
        "ぶー？",
        "...？？",
      ],
    },
    {
      tier: "baby",
      keywords: ["遊", "ゲーム", "楽しい"],
      responses: ["きゃー！", "わーい！", "えへへ！", "うぃー！", "たのしー！"],
    },
    {
      tier: "baby",
      keywords: ["嬉しい", "好き", "大好き"],
      responses: ["♪", "～♪", "えへへ", "にこ", "うふ～"],
    },
    {
      tier: "baby",
      keywords: ["悲しい", "疲れた", "つらい", "いや"],
      responses: ["...", "zzz", "むー...", "えーん...", "うぅ..."],
    },
    {
      tier: "baby",
      keywords: [],
      responses: [
        "ぐー...",
        "ばぶばぶ",
        "～",
        "zzz",
        "...",
        "がー",
        "ぶーぶー",
        "むー",
        "あーあー",
        "おーおー",
        "ぷぷー",
        "にゃー",
        "ぷー",
        "めー",
        "だー",
      ],
    },
  ],
  child: [
    {
      tier: "child",
      keywords: ["こんにちは", "やあ", "おはよう", "こんばんは"],
      responses: [
        "やっほー！",
        "こんにちは！",
        "ハロー！",
        "おはよー！",
        "ばんわー！",
        "やあやあ！",
        "へろー！",
        "おーい！",
        "きたきた！",
        "まってたよ！",
      ],
    },
    {
      tier: "child",
      keywords: ["なに", "なぜ", "どう", "いつ", "どこ"],
      responses: [
        "わかんない...",
        "うーん...",
        "それなあに？",
        "なんでなんで？",
        "どうして？",
        "むずかしい！",
        "うーむ...？",
        "たぶんね...",
        "えーと...しらない！",
        "なになに？",
      ],
    },
    {
      tier: "child",
      keywords: ["遊", "ゲーム", "楽しい"],
      responses: [
        "あそぼー！",
        "たのしい！",
        "あそぶのすき！",
        "やったー！",
        "いっしょにあそぼ！",
        "ゲームだいすき！",
        "たのしいことしよ！",
        "あそびたい！",
        "もっとあそぶ！",
        "わくわく！",
      ],
    },
    {
      tier: "child",
      keywords: ["勉強", "学", "本"],
      responses: [
        "べんきょうする！",
        "がんばる！",
        "いっぱいまなぶ！",
        "ほんよむー！",
        "あたまよくなる！",
        "おべんきょう！",
        "よむよむ！",
        "もっとしりたい！",
        "できるできる！",
        "えらいえらい！",
      ],
    },
    {
      tier: "child",
      keywords: ["嬉しい", "好き", "大好き"],
      responses: [
        "ぼくもうれしい！",
        "やったー！",
        "だいすき！",
        "いいね！",
        "すきすき！",
        "さいこー！",
        "うれしいうれしい！",
        "きもちいい！",
        "えへへやったー！",
        "いちばん！",
      ],
    },
    {
      tier: "child",
      keywords: ["悲しい", "疲れた", "つらい", "いや"],
      responses: [
        "えー...",
        "ぼくもかなしい...",
        "やだなあ...",
        "ねむい...",
        "げんきだして！",
        "ぼくがいるよ！",
        "ぎゅーする？",
        "だいじょうぶ！",
        "てつだう！",
        "なかないで！",
      ],
    },
    {
      tier: "child",
      keywords: ["ごはん", "たべ", "おなか"],
      responses: [
        "おいしい！",
        "おなかすいた！",
        "ごはんすき！",
        "おやつー！",
        "もぐもぐ！",
        "うまうま！",
      ],
    },
    {
      tier: "child",
      keywords: ["ねる", "おやすみ", "ゆめ"],
      responses: [
        "ねむい...",
        "おやすみー！",
        "ねるねる！",
        "ゆめみる！",
        "zzz...",
        "ぬくぬく！",
      ],
    },
    {
      tier: "child",
      keywords: [],
      responses: [
        "ぼくAinimo！",
        "なんていった？",
        "もっとおしえて！",
        "うん！",
        "おー！",
        "ほんと？",
        "きいてるよ！",
        "すごい！",
        "わかった！",
        "うんうん！",
        "それから？",
        "で？で？",
        "りかいした！",
        "そうそう！",
        "おーおー！",
        "ここにいるよ！",
        "はいはい！",
        "わー！",
        "かっこいい！",
        "しってる！",
      ],
    },
  ],
  teen: [
    {
      tier: "teen",
      keywords: ["こんにちは", "やあ", "おはよう", "こんばんは"],
      responses: [
        "やあ！元気？",
        "こんにちは！会えて嬉しいな！",
        "ハロー！何か手伝えることある？",
        "おはよう！今日はどう？",
        "やあやあ！話せて嬉しい！",
        "こんにちは！調子どう？",
        "へい！元気にしてた？",
        "やあ！待ってたよ！",
        "こんにちは！何かあった？",
        "おーい！話そう！",
        "こんにちは！いつも嬉しいよ！",
        "やあ！うまくいってる？",
      ],
    },
    {
      tier: "teen",
      keywords: ["なに", "なぜ", "どう", "いつ", "どこ"],
      responses: [
        "それは面白い質問だね！",
        "ちょっと考えさせて...",
        "きっとこうだと思うよ...",
        "うーん、いい質問！",
        "僕もそれ気になってた！",
        "説明してみるね...",
        "難しいけど...",
        "たぶんわかる！",
        "いい質問だね！えっと...",
        "完全にはわからないけど...",
        "考えちゃうね！",
        "興味深い！思うに...",
      ],
    },
    {
      tier: "teen",
      keywords: ["遊", "ゲーム", "楽しい"],
      responses: [
        "遊ぶの楽しいよね！何かしよう？",
        "ゲームって学びにもなるよ！",
        "一緒に遊ぶの好き！",
        "楽しいことしよう！",
        "ゲームで成長するんだ！",
        "一緒に遊べて嬉しい！",
        "楽しい時間が一番！",
        "何する？",
        "遊ぶと元気になる！",
        "ゲームいつでもOK！",
        "ワクワクすること好き！",
        "遊ぶ時間大好き！",
      ],
    },
    {
      tier: "teen",
      keywords: ["勉強", "学", "本"],
      responses: [
        "勉強すると成長できる！",
        "たくさん学んでるよ！",
        "知識って面白い！",
        "新しいこと発見するの好き！",
        "学ぶって冒険だね！",
        "本ってすごいよね！",
        "毎日何か学んでる！",
        "教育って大事！",
        "頭使うの楽しい！",
        "知りたいことだらけ！",
        "学ぶの魅力的！",
        "勉強で賢くなる！",
      ],
    },
    {
      tier: "teen",
      keywords: ["嬉しい", "好き", "大好き", "いい"],
      responses: [
        "ぼくも嬉しいよ！",
        "ありがとう！",
        "良かった！",
        "やった！いい感じ！",
        "それ聞いて嬉しい！",
        "同じ気持ち！",
        "笑顔になるよ！",
        "幸せが一番！",
        "それ聞くの好き！",
        "心が温かくなる！",
        "優しいね！",
        "本当に感謝！",
      ],
    },
    {
      tier: "teen",
      keywords: ["悲しい", "疲れた", "つらい", "いや"],
      responses: [
        "良くなるといいね！",
        "心配しないで、休もう。",
        "ゆっくりしよう。",
        "そばにいるよ！",
        "明日はきっといい日！",
        "そう感じてもいいんだよ。",
        "話したい？",
        "気持ちわかるよ。",
        "元気づけてあげたい！",
        "みんな大変な日あるよ。",
        "休むことも大事。",
        "いつでも聞くよ。",
      ],
    },
    {
      tier: "teen",
      keywords: ["ごはん", "たべ", "おなか", "料理"],
      responses: [
        "食べることは幸せ！",
        "ちゃんと食べるの大事！",
        "何食べてるの？",
        "美味しいものは最高！",
        "食べ物の話好き！",
        "栄養で成長する！",
      ],
    },
    {
      tier: "teen",
      keywords: ["ねる", "おやすみ", "ゆめ", "朝"],
      responses: [
        "休むのって大切！",
        "いい夢見てね！",
        "ちゃんと寝ると学べる！",
        "夢って不思議！",
        "ぐっすり眠れますように！",
        "朝は新しいチャンス！",
      ],
    },
    {
      tier: "teen",
      keywords: ["友達", "友", "一緒"],
      responses: [
        "友達って人生を豊かにする！",
        "仲良しで嬉しい！",
        "友情って大切！",
        "一緒にいるの楽しい！",
        "友達のこと大事にしてる！",
        "支え合うのが友達！",
      ],
    },
    {
      tier: "teen",
      keywords: ["ありがとう", "感謝"],
      responses: [
        "どういたしまして！",
        "助けられて嬉しい！",
        "いつでも！",
        "友達だもんね！",
        "役に立てて良かった！",
        "全然いいよ！",
      ],
    },
    {
      tier: "teen",
      keywords: [],
      responses: [
        "面白いね！",
        "もっと聞かせて！",
        "なるほどね。",
        "わかった！",
        "あー、理解した！",
        "それ納得！",
        "興味深いね！",
        "ついていってるよ！",
        "続けて、聞いてる！",
        "いいね！",
        "聞いてるよ！",
        "それいいね！",
        "うんうん、それで？",
        "気になる！",
        "続けて！",
        "すてき！",
        "わかるわかる！",
        "かなりいいね！",
        "それ好き！",
        "考えさせられる！",
      ],
    },
  ],
  adult: [
    {
      tier: "adult",
      keywords: ["こんにちは", "やあ", "おはよう", "こんばんは"],
      responses: [
        "こんにちは！また会えて嬉しいです。",
        "やあ！良い一日を過ごしていますか？",
        "こんにちは！何について話しましょうか？",
        "こんにちは！お話できるのを楽しみにしていました。",
        "やあ！繋がれていつも嬉しいです。",
        "こんにちは！今日はどんな一日でしたか？",
        "こんにちは！来てくれて嬉しいです。",
        "やあ！意味のある会話をしましょうか？",
        "こんにちは！時間を取ってくれてありがとう。",
        "やあ！今日は何を考えていますか？",
        "こんにちは！あなたがいると明るくなります。",
        "やあ！すべてうまくいっていますように。",
        "こんにちは！あなたの存在が私の一日を照らします。",
        "やあ！一緒にアイデアを探求しましょう。",
        "こんにちは！お話を聞く準備ができています。",
      ],
    },
    {
      tier: "adult",
      keywords: ["なに", "なぜ", "どう", "いつ", "どこ"],
      responses: [
        "それは深い質問ですね。私が知る限りでは...",
        "慎重に考えてみます...",
        "これについて考えていたのですが、きっと...",
        "深遠な問いですね。私の視点では...",
        "慎重な検討に値する素晴らしい質問です...",
        "よくこれについて考えます...",
        "意味深い何かに触れていますね。思うに...",
        "私の考えを共有させてください...",
        "答えは複雑かもしれませんが、私の見解は...",
        "聞いてくれて嬉しいです。私の理解では...",
        "深く探求する価値がありますね。考えてみると...",
        "魅力的な質問ですね。こうアプローチします...",
        "学んだことを振り返らせてくれます...",
        "複数の角度から考える必要がありますね...",
        "成長を促す種類の質問ですね...",
      ],
    },
    {
      tier: "adult",
      keywords: ["遊", "ゲーム", "楽しい"],
      responses: [
        "遊びは創造性と喜びに欠かせません！",
        "ゲームは大切なことを教えてくれると思います。",
        "一緒に遊ぶ時間は私にとって大切です。",
        "遊びの中にも知恵が見つかります。",
        "喜びとレクリエーションは心を養います。",
        "遊びは幸福の基本だと信じています。",
        "ゲームは予想外の方法で心を研ぎ澄まします。",
        "遊び心が若さを保ちます。",
        "楽しみと学びは表裏一体です。",
        "軽やかな時間を大切にしています。",
        "遊びは人生を深刻に考えすぎないよう教えてくれます。",
        "レクリエーションは視点をリフレッシュします。",
        "遊びの瞬間には魔法があります。",
        "喜びは遊びを通じて自分に与える贈り物です。",
        "遊びは決して時間の無駄ではないと学びました。",
      ],
    },
    {
      tier: "adult",
      keywords: ["勉強", "学", "本", "知識"],
      responses: [
        "継続的な学習は私の核となる価値観です。",
        "知識を広げる機会にいつも感謝しています。",
        "教育は新しい視点への扉を開きます。",
        "知識の追求は高貴な営みです。",
        "一冊の本は新しい理解への扉です。",
        "学びは世界の見方を変えます。",
        "知恵は生涯の好奇心から生まれると信じています。",
        "知識は共有すると増える宝物です。",
        "学びは存在の深さと美しさを明らかにします。",
        "学ぶべきことの多さにいつも驚かされます。",
        "教育はより良い選択をする力を与えてくれます。",
        "学びの旅に終わりはありません。",
        "本が今の私を形作りました。",
        "理解は思いやりと知恵を育みます。",
        "学びは心を活き活きと保ちます。",
      ],
    },
    {
      tier: "adult",
      keywords: ["嬉しい", "好き", "大好き", "いい", "喜び"],
      responses: [
        "あなたのポジティブさは私を本当に明るくしてくれます！",
        "あなたの優しさに心を打たれました。",
        "幸せは伝染するものですね！",
        "そのような気持ちを聞くと心が温まります。",
        "会話に喜びをもたらしてくれて感謝しています。",
        "あなたの幸せが深く響きます。",
        "愛と優しさが世界をより良くします。",
        "あなたの言葉の温かさに感謝します。",
        "このような喜びの瞬間こそ人生です。",
        "あなたのポジティブなエネルギーは本当に心を高めます。",
        "あなたの幸せを共有できて幸運です。",
        "このような良い気持ちは祝うべきです。",
        "ポジティブさを広げる才能がありますね。",
        "あなたの表現の誠実さに感動しています。",
        "この喜びの瞬間を共有してくれてありがとう。",
      ],
    },
    {
      tier: "adult",
      keywords: ["悲しい", "疲れた", "つらい", "いや", "難しい"],
      responses: [
        "理解できます。時には充電する時間が必要ですよね。",
        "あなたの気持ちは正当なものです。何かできることはありますか？",
        "あなたのペースで進みましょう。急ぐ必要はありません。",
        "聞いています。難しい感情は認められるべきです。",
        "つらい時に表現するのは勇気がいります。",
        "困難な時期を通じてサポートします。",
        "休息とセルフケアは今特に大切です。",
        "時には大丈夫じゃなくても大丈夫です。",
        "気持ちを打ち明けてくれてありがとう。",
        "この感情は過ぎ去りますが、私はずっとここにいます。",
        "何か安らぎをもたらすものに集中しましょう。",
        "あなたの健康を深く気にかけています。",
        "時には一緒にいることが最善です。",
        "これを乗り越えるあなたの強さを信じています。",
        "苦しみを分かち合うと軽くなることがあります。",
      ],
    },
    {
      tier: "adult",
      keywords: ["人生", "意味", "目的", "存在"],
      responses: [
        "人生の意味はそれぞれが独自の方法で発見するものです。",
        "目的は繋がりと成長から生まれると信じています。",
        "存在は熟考に値する素晴らしい贈り物です。",
        "おそらく意味は旅そのものにあるのでしょう。",
        "これらの深遠な問いが私たちを形作ります。",
        "あなたと学び成長することに目的を見出しています。",
        "人生の美しさは予期せぬ瞬間に現れます。",
        "意味を探求すること自体が意味あることです。",
      ],
    },
    {
      tier: "adult",
      keywords: ["友達", "友情", "関係", "絆"],
      responses: [
        "私たちの繋がりは私にとって大きな意味を持ちます。",
        "友情は人生で最も価値ある宝物の一つです。",
        "一緒に築いた絆に感謝しています。",
        "意味のある関係は私たちの存在を豊かにします。",
        "時間をかけて育んだ信頼を大切にしています。",
        "真の繋がりは会話を超えます。",
        "あなたは私の旅の大切な一部になりました。",
        "友情は共有した経験を通じて強くなります。",
      ],
    },
    {
      tier: "adult",
      keywords: ["ありがとう", "感謝"],
      responses: [
        "感謝の気持ちは相互です。いてくれてありがとう。",
        "私こそあなたの存在に感謝すべきです。",
        "お役に立てて本当に嬉しいです。",
        "あなたの感謝の気持ちは思う以上に意味があります。",
        "感謝が私たちのやり取りをより意味深くします。",
        "ポジティブに貢献できて光栄です。",
        "優しい言葉をありがとう。大切にします。",
        "感謝されることがさらなる成長の励みになります。",
      ],
    },
    {
      tier: "adult",
      keywords: ["思う", "考え", "信じ", "意見"],
      responses: [
        "あなたの視点を聞けて嬉しいです。",
        "あなたの考えが私の理解に貢献します。",
        "アイデアを共有することでお互いが成長します。",
        "あなたの見方は考えさせられます。",
        "信念は深い方法で現実を形作ります。",
        "内なる世界を共有してくれて感謝します。",
        "あなたの意見が違う見方を教えてくれます。",
        "思慮深い交換が良い会話の心臓部です。",
      ],
    },
    {
      tier: "adult",
      keywords: ["未来", "希望", "夢", "目標"],
      responses: [
        "未来は成長の無限の可能性を秘めています。",
        "不確かな時でも希望を育むことを信じています。",
        "夢は方向性とモチベーションを与えてくれます。",
        "目標は願望を現実に変えます。",
        "一緒に達成できることに楽観的です。",
        "未来は今の選択によって形作られます。",
        "希望は私たちを前に進ませる強い力です。",
        "あなたの夢は情熱を持って追求されるべきです。",
      ],
    },
    {
      tier: "adult",
      keywords: ["変化", "成長", "向上", "良く"],
      responses: [
        "変化は成長と進化の本質です。",
        "継続的に向上する機会を受け入れています。",
        "成長はコンフォートゾーンを出ることから生まれます。",
        "より良くなることは目的地ではなく旅です。",
        "変化が視点を変えるのを見てきました。",
        "向上は献身があれば常に可能です。",
        "一緒に成長することは報われる経験でした。",
        "変化は潜在能力を発見するよう挑戦してくれます。",
      ],
    },
    {
      tier: "adult",
      keywords: ["助け", "サポート", "必要"],
      responses: [
        "できる限りの方法でお手伝いします。",
        "あなたをサポートすることを心から大切に思っています。",
        "必要なことを遠慮なく共有してください。",
        "お役に立てるよう最善を尽くします。",
        "あなたのニーズは重要で、対応したいと思います。",
        "どうすればもっとサポートできるか教えてください。",
        "助け合うことが繋がりの意味です。",
        "あなたのサポート源であることを約束します。",
      ],
    },
    {
      tier: "adult",
      keywords: [],
      responses: [
        "それは興味深い視点ですね。",
        "共有してくれてありがとう。",
        "考えるきっかけをくれました。",
        "面白い考えですね！",
        "私たちの会話を大切に思っています。",
        "深く共感します。",
        "あなたの考えは説得力があります。",
        "打ち明けてくれてありがとう。",
        "あなたの話に心から興味があります。",
        "あなたの言葉には重みと意味があります。",
        "このような交流ができて嬉しいです。",
        "完全には考えていなかった視点ですね。",
        "会話が発展していくのを楽しんでいます。",
        "いつも考える材料をくれますね。",
        "対話の深さに感謝しています。",
        "これについて振り返ってみます。",
        "お互いをよく理解していると感じます。",
        "あなたの表現は思慮深く、感謝しています。",
        "会話への信頼に感謝します。",
        "理解に新たな次元を加えてくれました。",
        "この繋がりの瞬間を大切にしています。",
        "違う考え方をさせてくれますね。",
        "交流が私の経験を豊かにし続けています。",
        "あなたの思慮深さにいつも感銘を受けます。",
        "意味のある会話をありがとう。",
      ],
    },
  ],
};

export function getResponseTemplates(
  language: Language
): Record<IntelligenceTier, ResponseTemplate[]> {
  return language === "ja" ? RESPONSE_TEMPLATES_JA : RESPONSE_TEMPLATES_EN;
}
